### ISSUE TITLE
Capture and report more performance information

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-ssot#11]
### Environment
* Nautobot version:  1.1.3
* nautobot-ssot version:  1.0.1

### Proposed Functionality
Currently only the total duration of the Job execution is being captured and reported in the Sync Result view.

It would be great to have more information available to help identify any performance issue like  : 
- individual time to load each adapter
- time to execute the diff
- time to execute the sync
- memory utilized

 ### Use Case
Improve developer experience and help identify any performance issue

**Comment by chadell** [comment]
@dgarros I guess this issue is solved by #15?

**Comment by chadell** [comment]
Added in #15
