### ISSUE TITLE
Default `sync_data` function

### ISSUE THREAD

**Issue by dgarros** [nautobot/nautobot-plugin-ssot#12]
### Environment
* Nautobot version:  1.1.3
* nautobot-ssot version:  1.0.1

### Proposed Functionality
While looking at some recent projects that are built on top of the ssot plugin, I noticed that all `sync_data` function pretty much looks the same and have been copy/pasted from the documentation.

It feels like it would make sense to offer an option to the datasource developer to only define the source and the target adapter and have a standard/default sync_data function

### Use Case
Beyond the developer experience improvement, I think it would help to instrument the execution of the Job (#11) if we have a standard workflow.

**Comment by chadell** [comment]
@dgarros , is the refactor implemented in #15 enough? or is there any missing thing?

**Comment by chadell** [comment]
Implemented in #15
