### ISSUE TITLE
Migrate IP Fabric SSoT Plugin to This Repo

### ISSUE THREAD

**Issue by bryanculver** [nautobot/nautobot-plugin-ssot#130]
### Environment
* Nautobot version:  
* nautobot-plugin-chatops version:  

### Proposed Functionality

After #128 and #115, merge https://github.com/nautobot/nautobot-plugin-ssot-ipfabric into this repo as an `integration`.

### Use Case

Make installation, discovery, maintaining easier.

**Comment by snaselj** [comment]
Possible to finish #137 after nautobot-ssot with IP Fabric integration release.
