### ISSUE TITLE
Support Nautobot 1.2.0

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-plugin-ssot#17]
### Environment
* Nautobot version:  1.2.0
* nautobot-ssot version:  1.0.1

### Proposed Functionality

Add support for the new JobLogEntry table.

### Use Case

If Nautobot 1.2.0 is installed, the Job Logs within the SSOT Sync page will not load.

**Comment by chadell** [comment]
@smk4664 is this still relevant?

**Comment by smk4664** [comment]
I don't think so, I can't remember, but I believe this was resolved on the nautobot side

**Comment by chadell** [comment]
thanks @smk4664 !
