### ISSUE TITLE
Look into filtering per Nautobot constructs that applies to Infoblox as well

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot-plugin-ssot#170]
Currently there is tons of data that can be synced due to the amount of IP addresses and prefixes available.

We need to investigate how we can potentially map extrattrs on these objects to ones within Nautobot to narrow jobs to speed them up as well as limit the scope.

**Comment by jdrew82** [comment]
I think this is covered by #35 and #37 so we can close this out.
