### ISSUE TITLE
Show Running Jobs

### ISSUE THREAD

**Issue by justinjeffery-ipf** [nautobot/nautobot-plugin-ssot#195]
### Environment
* Nautobot version:  1.2.4
* nautobot-ssot-ipfabric version:  0.9.4

### Proposed Functionality
Nautobot GUI should show IP Fabric SSOT running jobs.  Currently it only lists Completed or Failed.  

### Use Case
If you navigate away from the sync details you have no way of knowing if a job is running or not.

**Comment by Kircheneer** [comment]
I take it this has been fixed then? Feel free to re-open if not. Thanks!
