### ISSUE TITLE
missing dependency structlog

### ISSUE THREAD

**Issue by alextremblay** [nautobot/nautobot-plugin-ssot#23]
### Environment
* Python version:  3.10
* Nautobot version:  1.2.3
* nautobot-ssot version:  1.0.1

`nautobot_ssot` would show up in plugins list after being installed

`nautobot_ssot` plugin not in plugins list, error in nautobot log:

```
File "/Users/alex/Projects/python/nautobot/.venv/lib/python3.10/site-packages/nautobot_ssot/jobs/__init__.py", line 7, in <module>
    from .base import DataSource, DataTarget
  File "/Users/alex/Projects/python/nautobot/.venv/lib/python3.10/site-packages/nautobot_ssot/jobs/base.py", line 14, in <module>
    import structlog
ModuleNotFoundError: No module named 'structlog'
```

### Steps to Reproduce
1. install `nautobot_ssot` as described in the documentation
2. start nautobot

**Comment by glennmatthews** [comment]
FWIW, `structlog` is supposed to be a transitive dependency that we pick up from our dependency on `diffsync` but we had a bad release 1.4.0 that was missing that dependency. Updating to `diffsync` 1.4.1 *should* fix this issue for you. Sorry for the trouble!

**Comment by alextremblay** [comment]
Ahhh, ok. Updating diffsync did indeed fix this problem. Thank you!
