### ISSUE TITLE
Job failure when including super().update(attrs) in the Nautobot adapter's update() method

### ISSUE THREAD

**Issue by nathanielfernandez** [nautobot/nautobot-plugin-ssot#233]
### Environment
* Python version: 3.9.16
* Nautobot version: v1.5.23
* nautobot-ssot version: 1.3.2

### However, when I include the super().update(attrs) in the update() method of my Nautobot adapter, the script fails with an error in the job that says "An error occurred while updating Nautobot: 'dict' object has no attribute 'get_type'"

The error seems to be on that super().update(attrs) line because if it is commented out, the sync of the device status between Orion and Nautobot works fine. At this point, I am not sure if this a mistake on how I called it or a bug. Looks like the update() method will just call itself again, but I'm not sure.

### Steps to Reproduce
1. In the update() method of the nautobot adapter, uncomment the line with 'super().update(attrs)' then commit + push to jobs repo.

```
class adapter_nautobot_b(DiffSync):
    """Example of a DiffSync adapter implementation."""

    device = Device
    top_level = ["device"]

    def load(self):
        """Initialize the Nautobot Object"""

        nautobot_devices = nb_device.objects.all()

        for d in nautobot_devices:
            # For this example, only use the devices in the SAMPLE site.
            if str(d.site) == "SAMPLE":
                device_entry = self.device(name=d.name, mgt_status = str(d.status))
                self.add(device_entry)


    def update(self, attrs):
        """Update the nautobot object"""
        dev = nb_device.objects.get(name=attrs["name"])
        s = attrs["mgt_status"].lower()
        status = Status.objects.get(slug=s)
        dev.status = status
        dev.validated_save()
        # return super().update(attrs)
```
![image](https://github.com/nautobot/nautobot-plugin-ssot/assets/93752762/01b99553-93e9-42d1-88a8-64cc15db75c5)

2. In Nautobot, perform a sync with the jobs repo, then perform a "nautobot-server post_upgrade" and "sudo systemctl restart nautobot nautobot-worker".
3. Run the SSoT job
4. The job would be a failure. In the logs of the job, there is an error message that says "An error occurred while updating Nautobot: 'dict' object has no attribute 'get_type'"

![image (3)](https://github.com/nautobot/nautobot-plugin-ssot/assets/93752762/5be422cc-e65c-4089-b64f-9d57853876a6)

**Comment by glennmatthews** [comment]
If I'm reading this right it seems like a mis-implementation to me - `DiffSync.update()` has the signature `(self, obj: DiffSyncModel)`; it's `DiffSyncModel.update()` that has the signature `(self, attrs: Dict)`. Can you check and confirm?

**Comment by nathanielfernandez** [comment]
Hi Glenn, thanks for looking at my issue. You're right, I showed my code to Justin Drew in nautobot slack. He pointed out I'm doing diffsync and just updating Nautobot. Looks like I would need to pattern my code first with the SSoT examples he showed me so I could properly use the update(self, attrs). Closing this issue now. Cheers!
