### ISSUE TITLE
Module nautobot_ssot.contrib is missing

### ISSUE THREAD

**Issue by nathanielfernandez** [nautobot/nautobot-plugin-ssot#247]
### Environment
* Python version:  3.9
* Nautobot version:  v1.5.23
* nautobot-ssot version:  1.3.2

I built this nautobot server and installed nautobot_ssot module on July 2023. I'm not yet using nautobot 2.0.0.

I was going to follow the quickstart example for developing data source and data target jobs (SSoT). I install the SSoT jobs via git. 

I'm getting an error when syncing the python job file I'm testing out for SSoT and it says `Error in loading Jobs from Sync Orion Device Status (SSoT): No module named 'nautobot_ssot.contrib'. I have nautobot_ssot but when I checked the contents of it under site-packages, I don't see contrib. Could I have missed installing a module?

```
[nautobot@server~]$ ls -lah /opt/nautobot/lib/python3.9/site-packages/nautobot_ssot/
total 108K
drwxr-x---   9 nautobot nautobot  318 Jul 19 22:02 .
drwxr-x--- 548 nautobot nautobot  24K Sep 14 23:23 ..
drwxr-x---   3 nautobot nautobot   44 Jul 19 22:02 api
-rw-r-----   1 nautobot nautobot  828 Jul 19 22:02 choices.py
-rw-r-----   1 nautobot nautobot 1.1K Jul 19 22:02 filters.py
-rw-r-----   1 nautobot nautobot 1.6K Jul 19 22:02 forms.py
-rw-r-----   1 nautobot nautobot 1.1K Jul 19 22:02 __init__.py
drwxr-x---   3 nautobot nautobot   78 Jul 19 22:02 jobs
-rw-r-----   1 nautobot nautobot 4.8K Jul 19 22:02 metrics.py
drwxr-x---   3 nautobot nautobot  175 Jul 19 22:02 migrations
-rw-r-----   1 nautobot nautobot 8.6K Jul 19 22:02 models.py
-rw-r-----   1 nautobot nautobot  601 Jul 19 22:02 navigation.py
drwxr-x---   2 nautobot nautobot 4.0K Jul 19 22:02 __pycache__
-rw-r-----   1 nautobot nautobot 6.4K Jul 19 22:02 tables.py
-rw-r-----   1 nautobot nautobot 1017 Jul 19 22:02 template_content.py
drwxr-x---   3 nautobot nautobot   27 Jul 19 22:02 templates
drwxr-x---   3 nautobot nautobot  147 Jul 19 22:02 templatetags
drwxr-x---   4 nautobot nautobot  186 Jul 19 22:02 tests
-rw-r-----   1 nautobot nautobot 1004 Jul 19 22:02 urls.py
-rw-r-----   1 nautobot nautobot 6.2K Jul 19 22:02 views.py
```

### Steps to Reproduce
1. In Extensibility > Git Repositories, attempt to sync the jobs repo to nautobot.
2. While syncing, there is an error being detected, which says module nautobot_ssot.contrib is missing.

**Comment by chadell** [comment]
The `nauboto_ssot.contrib` module was added in release 1.4.0 (you have 1.3.2): https://github.com/nautobot/nautobot-plugin-ssot/releases/tag/v1.4.0

**Comment by Kircheneer** [comment]
Closing for now, feel free to re-open if updating doesn't address the problem.

**Comment by nathanielfernandez** [comment]
Thank you and apologies, I wasn't able to close the issue right away. Our nautobot 1.x instance got hosed when I tried to upgrade the nautobot-ssot module to latest so I prioritized troubleshooting and rebuilding. I guess one of the dependencies in the latest nautobot-ssot module requires nautobot version 2.x. I should probably have used a version that fits 1.x.

**Comment by Kircheneer** [comment]
> Thank you and apologies, I wasn't able to close the issue right away.

No worries! Yes, indeed the latest version will only support 2.x (as it is impossible to support both simultaneously). The 1.6.x track tracks 1.x compatible, the 2.x track 2.x compatible versions.

**Comment by nathanielfernandez** [comment]
I see, that's how module versions are patterned... Well, at least I learned something from that experience. 😄

**Comment by Kircheneer** [comment]
I see that we may need to put some documentation effort here. Thanks!
