### ISSUE TITLE
Discussion: Base SSoT Job

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot-plugin-ssot#26]
I'm wondering if providing a base job with a `sync_data` method that loads the adapters, performs the diff, and implements the dry run functionality might be worth it?

This is more for a discussion to see if it's worth it as it may not be with some of the specifics for each plugin, but potentially people can use it to call `super()` after custom logic.

**Comment by glennmatthews** [comment]
FWIW #15 made some steps in this direction by adding the `load_source_adapter`, `load_target_adapter`, `calculate_diff`, and `execute_sync` methods. We need to get a 1.1.0 release out at some point soon so that people can begin making use of it.

**Comment by chadell** [comment]
@FragmentedPacket is this issue solved with the implementation or you have some missing points?

**Comment by chadell** [comment]
Done in #15
