### ISSUE TITLE
AssertionError at /graphql/

### ISSUE THREAD

**Issue by Danmanny** [nautobot/nautobot-plugin-ssot#274]
### Environment
* Python version:  3.10.13
* Nautobot version:  2.0.0
* nautobot-ssot version:  2.0.1

Work in a Nautobot v2.0.0 environment and access graphql.

Cannot access graphql

### Steps to Reproduce
1. Install Nautobot 2.0.0
2. Access Graphql

**Comment by jdrew82** [comment]
Investigated this and it appears to be related to some of the CustomFields being created in various integration signals. A few have dashes in the key when dashes will break GraphQL. CustomFields should always use underscores in keys.

**Comment by jeffkala** [comment]
Hit this as well with infoblox.

AssertionError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "cf_ssot-synced-to-infoblox" does not.

**Comment by jdrew82** [comment]
> Hit this as well with infoblox.
> 
> AssertionError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "cf_ssot-synced-to-infoblox" does not.

That's been found and is addressed in the fix PR.

**Comment by Kircheneer** [comment]
@jdrew82 does #275 cover all of these?

**Comment by jdrew82** [comment]
This should be resolved now so closing.
