### ISSUE TITLE
Arista custom fields should only be available for Arista devices

### ISSUE THREAD

**Issue by erjac77** [nautobot/nautobot-plugin-ssot#289]
### Environment
* Nautobot version:  2.0.5
* nautobot-ssot version:  2.0.1

### Proposed Functionality
Custom Fields such as `EOS Train` and `EOS Version` should only be available for Arista devices. Currently, the custom fields created by the AristaCV SSoT plugin appear for all devices.

A Dynamic Group may be required.
``` bash
(
  device_type__manufacturer__name='Arista'
)
```

### Use Case
Reduce irrelevant fields when creating/editing non-Arista devices.

**Comment by glennmatthews** [comment]
May be dependent on implementation of https://github.com/nautobot/nautobot/issues/889 to make this possible?

**Comment by jdrew82** [comment]
Yeah, this is an issue with Nautobot core, not the integration. This is a known issue with all CustomFields being displayed on all objects of a particular ContentType. The issue that @glennmatthews referenced is the discussion of the issue. As this isn't SSoT specific I'll close this out.
