### ISSUE TITLE
Add support for Mysql

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-plugin-ssot#59]
### Environment
* nautobot-ssot version:  1.1.2

### Proposed Functionality

Make base plugin usable with Mysql database, and add it's testing in the CI

### Use Case

Support Mysql database, as Nautobot is supporting it.

**Comment by Kircheneer** [comment]
Testing is in CI as of today: https://github.com/nautobot/nautobot-plugin-ssot/actions/runs/4873288189/jobs/8692799135
