### ISSUE TITLE
Consider SSoT Packaging

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot-plugin-ssot#83]
### Environment
* Nautobot version:  latest
* nautobot-ssot version:  latest

### Proposed Functionality

The ability to more easily manage all of the SSoT apps. This can come in many different forms

* An Ansible Collection like mechanism
* A package distrubution for the remote apps
* Move to a monolithic application
* Consolidation of the docs

### Use Case

The SSoT apps are growing pretty rapidly, in with that comes a large amount of maintainence:

* Redundant docs
* Keeping up with cookie cutter
* Keeping the ssot apps in sync with new features of SSoT

All of this takes time, makes it difficult to manage, and more likely to lead to issues down the road.

**Comment by itdependsnetworks** [comment]
Potentially consider Python entry points https://packaging.python.org/en/latest/specifications/entry-points/

**Comment by chadell** [comment]
This is already been worked out in #136 #137 #138 #139

**Comment by jdrew82** [comment]
I think we can consider this one resolved as all of the child repos have been integrated into this repo now.
