### ISSUE TITLE
Document how to efficiently load data from Nautobot

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-plugin-ssot#98]
### Environment
* Nautobot version:  all
* nautobot-ssot version: all

### Proposed Functionality

The documentation shows how to use features such as `Queryset.select_related` to use efficient DB queries in order to increase the performance of SSoT jobs.

### Use Case

Big SSoT jobs can take quite long. I would like them to be faster

### Example

```
for region in Region.objects.all():
    for site in Site.objects.filter(region=region):
        for location in Location.objects.filter(location_type__name="Floor", site=site):
            for sub_location in Location.objects.filter(location_type__name="Room", parent=location):
                pass
```

is quite slow, because it has a a query per `sub_location`.

```
for sub_location in Location.objects.filter(location_type__name="Room").select_related(
    "parent",
    "parent__site",
    "parent__site__region"
):
    pass
```

is just one big query with `JOIN`.

**Comment by chadell** [comment]
@Kircheneer , will you take care of this?
