### ISSUE TITLE
Nautobot 1.5.17 Incompatibility

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-plugin-ssot#99]
### Environment
* Python version:  3.10
* Nautobot version:  1.5.17
* nautobot-ssot version:  1.2.0

### Expected Behavior

Poetry should resolve dependencies

### Observed Behavior

```
Resolving dependencies...

Because nautobot (1.5.17) depends on packaging (>=23.0,<23.1)
 and nautobot-ssot (1.2.0) depends on packaging (>=21.3,<22.0), nautobot (1.5.17) is incompatible with nautobot-ssot (1.2.0).
So, because nautobot-ntc-managed-services depends on both nautobot (1.5.17) and nautobot-ssot (1.2.0), version solving failed.
```

### Steps to Reproduce
1.  Create pyproject.toml
2.  Update poetry lock file

**Comment by jdrew82** [comment]
There's also a problem with diffsync library being locked to 21.3. We need to have that one updated and then we can update SSoT.
